server:
  http_listen_port: 3105
  grpc_listen_port: 4320

storage:
  trace:
    backend: 's3'
    s3:
      endpoint: minio:9000
      insecure: true
      bucket: loki-data
      access_key: loki
      secret_key: supersecret
      forcepathstyle: true

ingester:
  trace_idle_period: 10s
  max_block_bytes: 50000

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4320
        http:
          endpoint: 0.0.0.0:4318
