services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      start-dev
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    ports:
      - "27017:27017"
  otel_collector:
    image: otel/opentelemetry-collector-contrib:0.117.0
    container_name: otel_collector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
  user_mgm:
    build: ./UserManagement
    ports:
      - "8081:8081"