"""work on budget tables

Revision ID: a9c200e913cb
Revises: d36db6ac0d4f
Create Date: 2025-02-18 16:10:29.583968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9c200e913cb'
down_revision: Union[str, None] = 'd36db6ac0d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('envelop_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_envelop_budgets_id'), 'envelop_budgets', ['id'], unique=False)
    op.create_table('percentage_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('needs_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wants_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('savings_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simple_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_envelops_id', table_name='envelops')
    op.drop_table('envelops')
    op.drop_column('budgets', 'target_total')
    op.drop_column('budgets', 'percentage_breakdown')
    op.drop_column('budgets', 'current_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('current_balance', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('percentage_breakdown', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('target_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_table('envelops',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('budget_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('allocated_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('spent_amount', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], name='envelops_budget_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='envelops_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='envelops_pkey')
    )
    op.create_index('ix_envelops_id', 'envelops', ['id'], unique=False)
    op.drop_table('simple_budgets')
    op.drop_table('percentage_budgets')
    op.drop_index(op.f('ix_envelop_budgets_id'), table_name='envelop_budgets')
    op.drop_table('envelop_budgets')
    # ### end Alembic commands ###
