"""add favicon to category

Revision ID: d36db6ac0d4f
Revises: 0188a281b05b
Create Date: 2025-02-13 15:22:59.230909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36db6ac0d4f'
down_revision: Union[str, None] = '0188a281b05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('favicon', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'favicon')
    # ### end Alembic commands ###
